# Generated by Django 4.2.11 on 2026-08-21 01:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("personal", "0001_initial"),
        ("common", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Position",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "position",
                    models.CharField(
                        max_length=100, verbose_name="Posición en la Empresa"
                    ),
                ),
                (
                    "observation",
                    models.TextField(blank=True, null=True, verbose_name="Observación"),
                ),
            ],
            options={
                "verbose_name": "Cargo",
            },
        ),
        migrations.CreateModel(
            name="RelationalPerson",
            fields=[
                (
                    "baseperson_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="common.baseperson",
                    ),
                ),
                (
                    "observation",
                    models.TextField(blank=True, null=True, verbose_name="Observación"),
                ),
                (
                    "type",
                    models.CharField(
                        blank=True,
                        choices=[("C", "Cliente"), ("O", "Contacto"), ("A", "Ambos")],
                        max_length=1,
                        null=True,
                        verbose_name="Tipo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Persona",
            },
            bases=("common.baseperson",),
        ),
        migrations.CreateModel(
            name="Relationship",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "observation",
                    models.TextField(blank=True, null=True, verbose_name="Observación"),
                ),
                (
                    "firefighter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="personal.firefighter",
                        verbose_name="Bombero Relacionado",
                    ),
                ),
                (
                    "relational_person",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="capitalrelacional.relationalperson",
                        verbose_name="Persona Relacionada",
                    ),
                ),
            ],
            options={
                "verbose_name": "Relación",
                "verbose_name_plural": "Relaciones",
            },
        ),
        migrations.CreateModel(
            name="RelationalCompany",
            fields=[
                (
                    "company_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="common.company",
                    ),
                ),
                (
                    "typecompany",
                    models.CharField(
                        choices=[
                            ("T", "Cuerpo de Bomberos"),
                            ("H", "Hospitales"),
                            ("R", "Grupos de Rescate"),
                            ("P", "Empresa Privada"),
                            ("U", "Dependencia USB"),
                            ("G", "Empresa Pública"),
                            ("C", "Agrupación Civil"),
                            ("O", "Otro"),
                        ],
                        max_length=1,
                        verbose_name="Tipo de Empresa",
                    ),
                ),
                (
                    "observation",
                    models.TextField(blank=True, null=True, verbose_name="Observación"),
                ),
                (
                    "type",
                    models.CharField(
                        blank=True,
                        choices=[("C", "Cliente"), ("O", "Contacto"), ("A", "Ambos")],
                        max_length=1,
                        null=True,
                        verbose_name="Tipo",
                    ),
                ),
                (
                    "person",
                    models.ManyToManyField(
                        through="capitalrelacional.Position",
                        to="capitalrelacional.relationalperson",
                    ),
                ),
            ],
            options={
                "verbose_name": "Empresa",
            },
            bases=("common.company",),
        ),
        migrations.AddField(
            model_name="position",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="capitalrelacional.relationalcompany",
                verbose_name="Compania",
            ),
        ),
        migrations.AddField(
            model_name="position",
            name="person",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="capitalrelacional.relationalperson",
                verbose_name="Persona",
            ),
        ),
    ]
