# Generated by Django 4.2.11 on 2026-08-21 01:07

import common.widgets
from django.db import migrations, models
import django.db.models.deletion
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "location",
                    models.TextField(blank=True, null=True, verbose_name="Detalle"),
                ),
                (
                    "map_location",
                    common.widgets.LocationField(
                        blank=True, max_length=255, verbose_name="Ubicación en Mapa"
                    ),
                ),
            ],
            options={
                "verbose_name": "Dirección",
                "verbose_name_plural": "Direcciones",
            },
        ),
        migrations.CreateModel(
            name="BasePerson",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(max_length=100, verbose_name="Primer Nombre"),
                ),
                (
                    "first_name_2",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Segundo Nombre",
                    ),
                ),
                (
                    "last_name",
                    models.CharField(max_length=100, verbose_name="Primer Apellido"),
                ),
                (
                    "last_name_2",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Segundo Apellido",
                    ),
                ),
                (
                    "id_document",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="Cédula"
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[("M", "Masculino"), ("F", "Femenino")],
                        max_length=2,
                        null=True,
                        verbose_name="Sexo",
                    ),
                ),
                (
                    "primary_email",
                    models.EmailField(
                        blank=True,
                        help_text="Si es bombero aqui va el email de bombero",
                        max_length=254,
                        null=True,
                        verbose_name="Email Principal",
                    ),
                ),
                (
                    "alternate_email",
                    models.EmailField(
                        blank=True,
                        help_text="Si es bombero aqui va su email personal",
                        max_length=254,
                        null=True,
                        verbose_name="Email Alterno",
                    ),
                ),
            ],
            options={
                "verbose_name": "Persona Min",
            },
        ),
        migrations.CreateModel(
            name="City",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250, verbose_name="Nombre")),
            ],
            options={
                "verbose_name": "Ciudad",
                "verbose_name_plural": "Ciudades",
            },
        ),
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Nombre")),
                (
                    "rif",
                    models.CharField(
                        blank=True, max_length=10, null=True, verbose_name="RIF"
                    ),
                ),
                (
                    "website",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Página Web"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, verbose_name="Email"
                    ),
                ),
                (
                    "address",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="common.address",
                        verbose_name="Dirección",
                    ),
                ),
            ],
            options={
                "verbose_name": "Compañia",
            },
        ),
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="Cargo")),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="common.company"
                    ),
                ),
            ],
            options={
                "verbose_name": "Trabajo",
            },
        ),
        migrations.CreateModel(
            name="School",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Nombre")),
            ],
            options={
                "verbose_name": "Institución Educativa",
                "verbose_name_plural": "Instituciones Educativas",
            },
        ),
        migrations.CreateModel(
            name="Suggestion",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField(auto_now=True, verbose_name="Fecha")),
                ("text", models.TextField(verbose_name="Sugerencia")),
            ],
        ),
        migrations.CreateModel(
            name="TelephoneNumber",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=4, verbose_name="Código")),
                ("number", models.CharField(max_length=7, verbose_name="Número")),
            ],
            options={
                "verbose_name": "Número Telefónico",
                "verbose_name_plural": "Números Telefónicos",
            },
        ),
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "baseperson_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="common.baseperson",
                    ),
                ),
                (
                    "birth_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha de Nacimiento"
                    ),
                ),
                (
                    "picture",
                    sorl.thumbnail.fields.ImageField(
                        blank=True,
                        null=True,
                        upload_to="images/persons/",
                        verbose_name="Foto",
                    ),
                ),
                (
                    "civil_state",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("S", "Soltero"),
                            ("C", "Casado"),
                            ("V", "Viudo"),
                            ("D", "Divorciado"),
                        ],
                        max_length=1,
                        null=True,
                        verbose_name="Estado Civil",
                    ),
                ),
            ],
            options={
                "verbose_name": "Persona",
            },
            bases=("common.baseperson",),
        ),
        migrations.CreateModel(
            name="PersonTelephoneNumber",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("T", "Trabajo"),
                            ("C", "Casa"),
                            ("M", "Celular"),
                            ("O", "Otro"),
                        ],
                        default="O",
                        max_length=1,
                        verbose_name="Tipo",
                    ),
                ),
                ("main", models.BooleanField(default=True, verbose_name="Principal")),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="common.baseperson",
                    ),
                ),
                (
                    "telephone_number",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="common.telephonenumber",
                    ),
                ),
            ],
            options={
                "verbose_name": "Número Telefónico",
                "verbose_name_plural": "Números Telefónicos",
            },
        ),
        migrations.CreateModel(
            name="Degree",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Nombre")),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("TSU", "Técnico Superior Universitario"),
                            ("PREG", "Pregrado (Licenciatura/Ingeniería)"),
                            ("DIP", "Diplomado"),
                            ("ESP", "Especialización"),
                            ("MAES", "Maestría"),
                            ("DOCT", "Doctorado"),
                            ("PDOC", "Postdoctorado"),
                        ],
                        max_length=4,
                        verbose_name="Tipo",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="common.school",
                        verbose_name="Institución",
                    ),
                ),
            ],
            options={
                "verbose_name": "Estudio",
            },
        ),
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Nombre")),
                ("hours", models.IntegerField()),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="common.school",
                        verbose_name="Institución",
                    ),
                ),
            ],
            options={
                "verbose_name": "Curso",
            },
        ),
        migrations.CreateModel(
            name="CompanyTelephoneNumber",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("main", models.BooleanField(default=True, verbose_name="Principal")),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="common.company"
                    ),
                ),
                (
                    "telephone_number",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="common.telephonenumber",
                    ),
                ),
            ],
            options={
                "verbose_name": "Número Telefónico",
                "verbose_name_plural": "Números Telefónicos",
            },
        ),
        migrations.AddField(
            model_name="address",
            name="city",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="common.city",
                verbose_name="Ciudad",
            ),
        ),
        migrations.CreateModel(
            name="PersonJob",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="Fecha de Inicio")),
                (
                    "end_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha de Finalización"
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="common.job",
                        verbose_name="Trabajo",
                    ),
                ),
                (
                    "supervisor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="supervised_set",
                        to="common.baseperson",
                        verbose_name="Supervisor",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="common.person",
                        verbose_name="Persona",
                    ),
                ),
            ],
            options={
                "verbose_name": "Trabajo",
            },
        ),
        migrations.CreateModel(
            name="PersonDegree",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateField(verbose_name="Fecha de Inicio")),
                (
                    "end_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha de Finalización"
                    ),
                ),
                (
                    "picture",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="images/degrees/",
                        verbose_name="Imagen Título",
                    ),
                ),
                (
                    "degree",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="common.degree",
                        verbose_name="Estudio",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="common.person",
                        verbose_name="Persona",
                    ),
                ),
            ],
            options={
                "verbose_name": "Estudio",
            },
        ),
        migrations.CreateModel(
            name="PersonCourse",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="Fecha de Realización")),
                (
                    "picture",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="images/courses/",
                        verbose_name="Imagen Certificado",
                    ),
                ),
                (
                    "training_course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="common.course",
                        verbose_name="Curso",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="common.person",
                        verbose_name="Persona",
                    ),
                ),
            ],
            options={
                "verbose_name": "Curso",
            },
        ),
        migrations.CreateModel(
            name="PersonAddress",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("C", "Casa"), ("T", "Trabajo"), ("O", "Otro")],
                        max_length=1,
                        verbose_name="Tipo",
                    ),
                ),
                (
                    "address",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="common.address",
                        verbose_name="Dirección",
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="common.person",
                        verbose_name="Persona",
                    ),
                ),
            ],
            options={
                "verbose_name": "Dirección",
                "verbose_name_plural": "Direcciones",
            },
        ),
        migrations.AddField(
            model_name="person",
            name="addresses",
            field=models.ManyToManyField(
                null=True,
                through="common.PersonAddress",
                to="common.address",
                verbose_name="Direcciones",
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="birth_place",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="born_here",
                to="common.address",
                verbose_name="Lugar de Nacimiento",
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="childs",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="child_set",
                to="common.baseperson",
                verbose_name="Hijos",
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="courses",
            field=models.ManyToManyField(
                null=True,
                through="common.PersonCourse",
                to="common.course",
                verbose_name="Cursos",
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="degrees",
            field=models.ManyToManyField(
                null=True,
                through="common.PersonDegree",
                to="common.degree",
                verbose_name="Estudios",
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="jobs",
            field=models.ManyToManyField(
                null=True,
                through="common.PersonJob",
                to="common.job",
                verbose_name="Trabajos",
            ),
        ),
    ]
