# Generated by Django 4.2.11 on 2026-08-27 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("personal", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Communication",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Título")),
                ("body", models.TextField(verbose_name="Contenido")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de publicación"
                    ),
                ),
                (
                    "pinned",
                    models.BooleanField(
                        default=False, verbose_name="Fijada (importante)"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="communications",
                        to="personal.firefighter",
                        verbose_name="Publicado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Comunicación",
                "verbose_name_plural": "Comunicaciones",
                "ordering": ["-pinned", "-created_at"],
            },
        ),
    ]
