# Generated by Django 4.2.11 on 2026-08-21 01:07

import common.widgets
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("personal", "0001_initial"),
        ("common", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("creation_date", models.DateTimeField(auto_now=True)),
                ("date", models.DateField(verbose_name="Fecha de inicio")),
                (
                    "time",
                    models.TimeField(help_text="HHMM", verbose_name="Hora de inicio"),
                ),
                (
                    "scene_arrival_date",
                    models.DateField(
                        null=True, verbose_name="Fecha de llegada al sitio"
                    ),
                ),
                (
                    "scene_arrival_time",
                    models.TimeField(
                        help_text="HHMM",
                        null=True,
                        verbose_name="Hora de llegada al sitio",
                    ),
                ),
                (
                    "end_date",
                    models.DateField(
                        null=True,
                        verbose_name="Fecha de regreso a la estación (Fin del Servicio)",
                    ),
                ),
                (
                    "end_time",
                    models.TimeField(
                        help_text="HHMM",
                        null=True,
                        verbose_name="Hora de regreso a la estación (Fin del Servicio)",
                    ),
                ),
                (
                    "service_type",
                    models.CharField(
                        choices=[
                            ("CM", "Control Médico"),
                            ("AME1", "Atención Médica de Emergencia"),
                            ("AME2", "Atención Médica de Enfermo"),
                            ("IDE", "Incendio de Estructura"),
                            ("IDV", "Incendio de Vegetación"),
                            ("PC", "Prevención y Control"),
                            ("AY", "Apoyo a la comunidad"),
                            ("MP", "Matpel"),
                            ("RES1", "Rescate de Personas"),
                            ("RES2", "Rescate Animal"),
                            ("SE", "Servicio Especial"),
                            ("GP", "Guardia de Prevención"),
                            ("NSA", "No se actuó"),
                            ("FA", "Falsa Alarma"),
                        ],
                        max_length=6,
                        verbose_name="Tipo",
                    ),
                ),
                ("description", models.TextField(verbose_name="Descripción")),
                (
                    "location",
                    models.TextField(blank=True, null=True, verbose_name="Dirección"),
                ),
                (
                    "map_location",
                    common.widgets.LocationField(
                        blank=True, max_length=255, verbose_name="Ubicación en Mapa"
                    ),
                ),
            ],
            options={
                "verbose_name": "Servicio",
                "verbose_name_plural": "Servicios",
                "ordering": ["-date", "-time"],
            },
        ),
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Nombre de Unidad"),
                ),
                ("active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Vehiculo",
                "verbose_name_plural": "Vehiculos",
            },
        ),
        migrations.CreateModel(
            name="ServiceVehicle",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "crew",
                    models.ManyToManyField(
                        blank=True,
                        null=True,
                        related_name="in_services",
                        to="personal.firefighter",
                        verbose_name="Tripulación",
                    ),
                ),
                (
                    "driver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="services_drove",
                        to="personal.firefighter",
                        verbose_name="Conductor",
                    ),
                ),
                (
                    "lead",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="services_lead",
                        to="personal.firefighter",
                        verbose_name="Jefe de Servicio",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vehicles",
                        to="ops.service",
                        verbose_name="Servicio",
                    ),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ops.vehicle",
                        verbose_name="Unidad",
                    ),
                ),
            ],
            options={
                "verbose_name": "Unidad en Servicio",
                "verbose_name_plural": "Unidades en Servicio",
            },
        ),
        migrations.CreateModel(
            name="ServiceImage",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    sorl.thumbnail.fields.ImageField(
                        upload_to="images/services/", verbose_name="Foto"
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="ops.service",
                        verbose_name="Servicio",
                    ),
                ),
                (
                    "uploader",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="personal.firefighter",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ServiceAffected",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("notes", models.TextField(verbose_name="Notas/Tratamiento")),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("EST", "Estudiante de la USB"),
                            ("PROF", "Profesor de la USB"),
                            ("EMP", "Empleado de la USB"),
                            ("OBR", "Obrero de la USB"),
                            ("NA", "Externo"),
                        ],
                        max_length=6,
                        verbose_name="Tipo",
                    ),
                ),
                (
                    "person_affected",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="services_involved",
                        to="common.baseperson",
                    ),
                ),
            ],
            options={
                "verbose_name": "Afectado",
                "verbose_name_plural": "Afectados",
            },
        ),
        migrations.AddField(
            model_name="service",
            name="affected",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                to="ops.serviceaffected",
                verbose_name="Afectados",
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                editable=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="services_created",
                to="personal.firefighter",
            ),
        ),
        migrations.CreateModel(
            name="ArrestPayment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("creation_date", models.DateTimeField(auto_now=True)),
                (
                    "start_time",
                    models.DateTimeField(verbose_name="Fecha/Hora de inicio"),
                ),
                ("end_time", models.DateTimeField(verbose_name="Fecha/Hora de fin")),
                (
                    "minutes",
                    models.IntegerField(
                        editable=False,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Minutos",
                    ),
                ),
                (
                    "approved_by_ops",
                    models.BooleanField(
                        default=True, verbose_name="Aprobado por Operaciones"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="arrest_payments_created",
                        to="personal.firefighter",
                        verbose_name="Agregado por",
                    ),
                ),
                (
                    "payer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="arrests_payments",
                        to="personal.firefighter",
                        verbose_name="Persona que paga el arresto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pago de Arresto",
                "verbose_name_plural": "Pagos de Arresto",
            },
        ),
        migrations.CreateModel(
            name="Arrest",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("creation_date", models.DateTimeField(auto_now=True)),
                ("date", models.DateField(verbose_name="Fecha")),
                ("description", models.TextField(verbose_name="Descripción")),
                (
                    "was_notified",
                    models.BooleanField(default=False, verbose_name="Notificó"),
                ),
                (
                    "time",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Minutos de ausencia",
                    ),
                ),
                (
                    "minutes",
                    models.IntegerField(
                        editable=False,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Minutos de arresto",
                    ),
                ),
                (
                    "approved_by_ops",
                    models.BooleanField(
                        default=True, verbose_name="Aprobado por Operaciones"
                    ),
                ),
                (
                    "approved_by_inspector",
                    models.BooleanField(
                        default=True, verbose_name="Aprobado por el Inspector"
                    ),
                ),
                (
                    "arrested",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="arrests",
                        to="personal.firefighter",
                        verbose_name="Arrestado",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="arrests_created",
                        to="personal.firefighter",
                        verbose_name="Agregado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Arresto",
                "verbose_name_plural": "Arrestos",
            },
        ),
    ]
