# Generated by Django 4.2.11 on 2026-08-27 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ops", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="service_type",
            field=models.CharField(
                choices=[
                    ("AER", "Falla de Aeronave"),
                    ("COMB", "Derrame de Combustible (Jet-A1)"),
                    ("MED", "Emergencia Médica (Terminal/Plataforma)"),
                    ("INC", "Incendio en Estructura/Plataforma"),
                    ("ALM", "Falsa Alarma / Activación de Detector"),
                    ("SIM", "Simulacro Regulatorio (RAP 314/OACI)"),
                    ("MP", "Matpel"),
                    ("RES1", "Rescate de Personas"),
                    ("SE", "Servicio Especial"),
                    ("GP", "Guardia de Prevención"),
                    ("NSA", "No se actuó"),
                    ("CM", "Control Médico"),
                    ("AME1", "Atención Médica de Emergencia"),
                    ("AME2", "Atención Médica de Enfermo"),
                    ("IDE", "Incendio de Estructura"),
                    ("IDV", "Incendio de Vegetación"),
                    ("PC", "Prevención y Control"),
                    ("AY", "Apoyo a la comunidad"),
                    ("RES2", "Rescate Animal"),
                    ("FA", "Falsa Alarma"),
                ],
                max_length=6,
                verbose_name="Tipo",
            ),
        ),
    ]
