# Generated by Django 4.2.11 on 2026-08-21 01:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("common", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Condecoration",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30, verbose_name="Nombre")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Descripción"),
                ),
            ],
            options={
                "verbose_name": "Condecoración",
                "verbose_name_plural": "Condecoraciones",
            },
        ),
        migrations.CreateModel(
            name="Condition",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30, verbose_name="Nombre")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Descripción"),
                ),
            ],
            options={
                "verbose_name": "Condición",
                "verbose_name_plural": "Condiciones",
            },
        ),
        migrations.CreateModel(
            name="Firefighter",
            fields=[
                (
                    "person_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="common.person",
                    ),
                ),
                (
                    "blood_type",
                    models.CharField(
                        blank=True,
                        choices=[("O", "O"), ("A", "A"), ("B", "B"), ("AB", "AB")],
                        max_length=2,
                        null=True,
                        verbose_name="Factor Sanguineo",
                    ),
                ),
                (
                    "blood_type_rh",
                    models.CharField(
                        blank=True,
                        choices=[("+", "Positivo"), ("-", "Negativo")],
                        max_length=1,
                        null=True,
                        verbose_name="RH",
                    ),
                ),
                (
                    "initials",
                    models.CharField(
                        blank=True, max_length=4, null=True, verbose_name="Iniciales"
                    ),
                ),
                (
                    "number",
                    models.SmallIntegerField(
                        blank=True, null=True, verbose_name="Carnet de Bombero"
                    ),
                ),
                (
                    "profile_picture",
                    sorl.thumbnail.fields.ImageField(
                        blank=True,
                        help_text="Asegurate de que el nombre del archivo no contenga acentos o eñes",
                        null=True,
                        upload_to="images/firefighter/",
                        verbose_name="Foto de Perfil",
                    ),
                ),
            ],
            options={
                "verbose_name": "Bombero",
                "ordering": ["-number", "last_name"],
            },
            bases=("common.person",),
        ),
        migrations.CreateModel(
            name="Rank",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("abrev", models.CharField(max_length=12)),
                ("type", models.CharField(max_length=20)),
            ],
            options={
                "verbose_name": "Rango",
            },
        ),
        migrations.CreateModel(
            name="RankChange",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="Fecha")),
                (
                    "link_to_doc",
                    models.URLField(
                        blank=True, null=True, verbose_name="Link al comunicado"
                    ),
                ),
                (
                    "firefighter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="personal.firefighter",
                    ),
                ),
                (
                    "rank_obtained",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="personal.rank",
                        verbose_name="Rango Obtenido",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ascenso",
                "ordering": ["date"],
            },
        ),
        migrations.AddField(
            model_name="firefighter",
            name="ranks",
            field=models.ManyToManyField(
                null=True,
                through="personal.RankChange",
                to="personal.rank",
                verbose_name="Rangos",
            ),
        ),
        migrations.AddField(
            model_name="firefighter",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="ConditionChange",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="Fecha")),
                (
                    "link_to_doc",
                    models.URLField(
                        blank=True, null=True, verbose_name="Link al comunicado"
                    ),
                ),
                (
                    "condition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="personal.condition",
                        verbose_name="Condición",
                    ),
                ),
                (
                    "firefighter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="condition_changes",
                        to="personal.firefighter",
                        verbose_name="Bombero",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cámbio de Condición",
                "verbose_name_plural": "Cambios de Condición",
                "ordering": ["date"],
            },
        ),
        migrations.CreateModel(
            name="CondecorationAward",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="Fecha")),
                (
                    "link_to_doc",
                    models.URLField(
                        blank=True, null=True, verbose_name="Link al comunicado"
                    ),
                ),
                (
                    "condecoration",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="personal.condecoration",
                        verbose_name="Condecoración",
                    ),
                ),
                (
                    "firefighter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="personal.firefighter",
                        verbose_name="Bombero",
                    ),
                ),
            ],
            options={
                "verbose_name": "Otorgamiento de Condecoración",
                "verbose_name_plural": "Otorgamientos de Condecoracion",
                "ordering": ["date"],
            },
        ),
        migrations.CreateModel(
            name="FirefighterHoliday",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_at", models.DateField(db_index=True, verbose_name="Desde")),
                ("end_at", models.DateField(db_index=True, verbose_name="Hasta")),
                (
                    "link_to_doc",
                    models.URLField(
                        blank=True, null=True, verbose_name="Link al comunicado"
                    ),
                ),
                (
                    "firefighter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="holidays",
                        to="personal.firefighter",
                        verbose_name="Bombero",
                    ),
                ),
            ],
            options={
                "verbose_name": "Días de Permiso",
                "verbose_name_plural": "Días de Permiso",
                "ordering": ["start_at"],
                "unique_together": {("firefighter", "start_at", "end_at")},
            },
        ),
    ]
